server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location / {
        return 503;
    }

    error_page 503 @maintenance;
    location @maintenance {
        rewrite ^(.*)$ /maintenance.html break;
        add_header Retry-After 7200 always;
        add_header Cache-Control "no-store" always;
    }
}
